use_frameworks!

platform :ios, '9.0'

target 'LYCustomKit_Example' do
  pod 'LYCustomKit', :path => '../'

  target 'LYCustomKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
